name: '@ianmstew'
markdown: redcarpet
exclude:
  - less
  - .gitignore
  - README.md
  - bower_components
  - node_modules
  - bower.json
  - package.json
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
